# Forcing refresh
steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/triodos-repo/triodos-ingestor:$COMMIT_SHA', '.']

# 2. Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west4-docker.pkg.dev/$PROJECT_ID/triodos-repo/triodos-ingestor:$COMMIT_SHA']

# 3. Update the Cloud Run Job with the new image
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'jobs'
    - 'update'
    - 'triodos-data-ingestor'
    - '--image'
    - 'europe-west4-docker.pkg.dev/$PROJECT_ID/triodos-repo/triodos-ingestor:$COMMIT_SHA'
    - '--region'
    - 'europe-west4'
  # Add this line to specify the service account for this step
  serviceAccount: 'projects/teak-truck-466313-g1/serviceAccounts/firestore-writer@teak-truck-466313-g1.iam.gserviceaccount.com'

# Store the image in Artifact Registry
images:
- 'europe-west4-docker.pkg.dev/$PROJECT_ID/triodos-repo/triodos-ingestor:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
